CREATE DATABASE LIBRERIA;
USE LIBRERIA;

CREATE TABLE  LIBRERIA.LIBROS
(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TITULO VARCHAR(40) NOT NULL,
AUTOR VARCHAR(30) NOT NULL,
EDITORIAL VARCHAR(20) NOT NULL,
PRECIO DECIMAL(5,2) NOT NULL
);

USE LIBRERIA;
CREATE PROCEDURE `UPDATE_PRECIO`(IN `EDIT` VARCHAR(20)) 
NOT DETERMINISTIC MODIFIES SQL DATA SQL SECURITY DEFINER 
	UPDATE LIBRERIA.LIBROS 
	SET PRECIO = (PRECIO*1.10) WHERE EDITORIAL = EDIT;



USE LIBRERIA;
CREATE PROCEDURE `UPDATE_PRECIO_TEN`(IN `EDIT` VARCHAR(20), IN `PLUS` INT) 
NOT DETERMINISTIC MODIFIES SQL DATA SQL SECURITY DEFINER 
	UPDATE LIBRERIA.LIBROS 
	SET PRECIO = (PRECIO+PLUS) WHERE EDITORIAL = EDIT;

